ci: Disable prepare_images.yml for now
Building environment images: 100%|██████████| 4/4 [02:28<00:00, 37.11s/it]
Traceback (most recent call last):
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/urllib3/response.py", line 748, in _error_catcher
All environment images built successfully.
    yield
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/urllib3/response.py", line 1206, in read_chunked
    self._update_chunk_length()
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/urllib3/response.py", line 1125, in _update_chunk_length
    line = self._fp.fp.readline()  # type: ignore[union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py", line 720, in readinto
Built images: sweb.env.x86_64.cc47cc71483942d0c3a15e:latest, sweb.env.x86_64.c795f4b88616b8462021ed:latest, sweb.env.x86_64.e83e37f52c09532c62acfb:latest, sweb.env.x86_64.aa92880033da20ca313928:latest
Pushing ghcr.io/getappmap/sweb.env.x86_64.c795f4b88616b8462021ed:latest
Pushing ghcr.io/getappmap/sweb.env.x86_64.e83e37f52c09532c62acfb:latest
Pushing ghcr.io/getappmap/sweb.env.x86_64.cc47cc71483942d0c3a15e:latest
Pushing ghcr.io/getappmap/sweb.env.x86_64.aa92880033da20ca313928:latest
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/urllib3/response.py", line 1057, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/urllib3/response.py", line 1189, in read_chunked
    with self._error_catcher():
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/runner/work/navie-benchmark/navie-benchmark/venv/lib/python3.12/site-packages/urllib3/response.py", line 753, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.